#!/bin/sh /etc/rc.common
# Copyright (C) 2024 Hackstop

START=99
STOP=85

USE_PROCD=1
PROG="/root/ips/protect.sh"

start_service() {
    echo "################### Starting HUND IPS service ####################"
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

